# Generated by Django 4.2 on 2023-04-12 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_squashed_0005_alter_species_options_alter_bug_species_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Specie',
            new_name='Species',
        ),
        migrations.AlterModelOptions(
            name='species',
            options={},
        ),
        migrations.RenameField(
            model_name='bug',
            old_name='detail',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='bug',
            old_name='specs',
            new_name='facts',
        ),
        migrations.RemoveField(
            model_name='bug',
            name='color',
        ),
        migrations.RemoveField(
            model_name='bug',
            name='size',
        ),
        migrations.RemoveField(
            model_name='bug',
            name='slug',
        ),
        migrations.AddField(
            model_name='bug',
            name='factnum',
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
    ]
