# Generated by Django 4.2 on 2023-04-12 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_rename_specie_species_alter_species_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bug',
            old_name='title',
            new_name='name',
        ),
    ]
