# Generated by Django 4.2 on 2023-04-20 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_aboutus'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutus',
            options={'verbose_name_plural': 'AboutUs'},
        ),
    ]
