# Generated by Django 4.2 on 2023-04-20 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_aboutus_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='species',
            options={'verbose_name_plural': 'Species'},
        ),
    ]
